//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsAdviser {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarsAdviser.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите закрыть приложение?.
        /// </summary>
        internal static string AskExit {
            get {
                return ResourceManager.GetString("AskExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите выйти из аккаунта?.
        /// </summary>
        internal static string AskLogOut {
            get {
                return ResourceManager.GetString("AskLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина успешно добавлена.
        /// </summary>
        internal static string carAdded {
            get {
                return ResourceManager.GetString("carAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина добавлена в закладки.
        /// </summary>
        internal static string carAddedBookmarks {
            get {
                return ResourceManager.GetString("carAddedBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина добавлена в скрытые.
        /// </summary>
        internal static string carAddedHidden {
            get {
                return ResourceManager.GetString("carAddedHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина уже находится в закладках.
        /// </summary>
        internal static string carAlreadyBookmarks {
            get {
                return ResourceManager.GetString("carAlreadyBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина уже находится в списке скрытых авто.
        /// </summary>
        internal static string carAlreadyHidden {
            get {
                return ResourceManager.GetString("carAlreadyHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение загружено.
        /// </summary>
        internal static string carImageUploaded {
            get {
                return ResourceManager.GetString("carImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина удалена из закладок.
        /// </summary>
        internal static string carRemovedFromBookmarks {
            get {
                return ResourceManager.GetString("carRemovedFromBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Машина удалена из скрытых.
        /// </summary>
        internal static string carRemovedFromHidden {
            get {
                return ResourceManager.GetString("carRemovedFromHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Город.
        /// </summary>
        internal static string cityPlaceHolder {
            get {
                return ResourceManager.GetString("cityPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код подтверждения.
        /// </summary>
        internal static string codePlaceHolder {
            get {
                return ResourceManager.GetString("codePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код подтверждения отправлен на вашу электронную почту.
        /// </summary>
        internal static string codeSended {
            get {
                return ResourceManager.GetString("codeSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка при отправке кода подтверждения.
        /// </summary>
        internal static string codeSendError {
            get {
                return ResourceManager.GetString("codeSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный или не сгенерированный код. Нажмите на кнопку генерации еще раз или проверьте правильность введенного кода.
        /// </summary>
        internal static string codeUncorrect {
            get {
                return ResourceManager.GetString("codeUncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка подключения к базе данных.
        /// </summary>
        internal static string databaseConnectionError {
            get {
                return ResourceManager.GetString("databaseConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные изменены.
        /// </summary>
        internal static string DataChanged {
            get {
                return ResourceManager.GetString("DataChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный адрес электронной почты!.
        /// </summary>
        internal static string EnterValidMail {
            get {
                return ResourceManager.GetString("EnterValidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите корректный номер телефона!.
        /// </summary>
        internal static string EnterValidPhone {
            get {
                return ResourceManager.GetString("EnterValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизация.
        /// </summary>
        internal static string formText {
            get {
                return ResourceManager.GetString("formText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение не загружено.
        /// </summary>
        internal static string ImageNotLoaded {
            get {
                return ResourceManager.GetString("ImageNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение загружено\nОбновите страницу или выйдите из аккаунта чтобы увидеть изменения.
        /// </summary>
        internal static string ImageUploaded {
            get {
                return ResourceManager.GetString("ImageUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail или телефон.
        /// </summary>
        internal static string loginPlaceHolder {
            get {
                return ResourceManager.GetString("loginPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string messageBoxError {
            get {
                return ResourceManager.GetString("messageBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        internal static string messageBoxInfo {
            get {
                return ResourceManager.GetString("messageBoxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string namePlaceHolder {
            get {
                return ResourceManager.GetString("namePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пароль.
        /// </summary>
        internal static string newPasswordPlaceHolder {
            get {
                return ResourceManager.GetString("newPasswordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль изменен.
        /// </summary>
        internal static string passwordChanged {
            get {
                return ResourceManager.GetString("passwordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string passwordPlaceHolder {
            get {
                return ResourceManager.GetString("passwordPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        internal static string patronymicPlaceHolder {
            get {
                return ResourceManager.GetString("patronymicPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string phonePlaceHolder {
            get {
                return ResourceManager.GetString("phonePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все предпочтения удалены.
        /// </summary>
        internal static string preferencesDeleted {
            get {
                return ResourceManager.GetString("preferencesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпочтения учтены.
        /// </summary>
        internal static string preferencesTaken {
            get {
                return ResourceManager.GetString("preferencesTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оценка сохранена.
        /// </summary>
        internal static string ratingSaved {
            get {
                return ResourceManager.GetString("ratingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаунт успешно создан.
        /// </summary>
        internal static string RegisterAccountSuccess {
            get {
                return ResourceManager.GetString("RegisterAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле поиска пустое.
        /// </summary>
        internal static string searchFieldEmpty {
            get {
                return ResourceManager.GetString("searchFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите язык.
        /// </summary>
        internal static string selectLang {
            get {
                return ResourceManager.GetString("selectLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        internal static string surnamePlaceHolder {
            get {
                return ResourceManager.GetString("surnamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход не удался
        ///
        ///Неправильный логин или пароль.
        /// </summary>
        internal static string uncorrectData {
            get {
                return ResourceManager.GetString("uncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена &lt;от&gt; должна быть меньше чем &lt;до&gt;.
        /// </summary>
        internal static string wrongPrices {
            get {
                return ResourceManager.GetString("wrongPrices", resourceCulture);
            }
        }
    }
}
